language: node_js
node_js: 'lts/*'
cache:
  directories:
    - 'node_modules' # This will tell Travis CI to cache the dependencies
dist: trusty
sudo: required

script: npm test # Here you could also run the build step of your application

before_deploy: npm install now --no-save # Install Now CLI on Travis

deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: now --prod
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now --prod
    skip_cleanup: true
    on:
      master: true